Develop
CrunchyData/crunchy-containers pull request #1124
Opened 2019-09-27 18:25 UTC by thesteve0

Trying to get the appdev image to build  - needs someone to run the test (I am only on windows machines today)

2019-09-28 20:19 UTC, jkatz requested changes
Tried building on CentOS 7. A few comments:

1. With the correction in the file mentioned in the comments, I get up to this error before it fails:

```sh
Transaction check error:
  file /usr/pgsql-11/lib/address_standardizer.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/lib/bitcode/address_standardizer.index.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/lib/bitcode/address_standardizer/analyze.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/lib/bitcode/address_standardizer/parseaddress-api.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/lib/bitcode/address_standardizer/std_pg_hash.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/lib/liblwgeom.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/lib/postgis-2.4.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/lib/postgis_topology-2.4.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/lib/rtpostgis-2.4.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/share/extension/address_standardizer.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/share/extension/address_standardizer_data_us.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/share/extension/address_standardizer_data_us.sql conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/share/extension/postgis.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/share/extension/postgis_sfcgal.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/share/extension/postgis_tiger_geocoder.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
  file /usr/pgsql-11/share/extension/postgis_topology.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64

Error Summary
-------------

error building at STEP "RUN yum -y update && yum -y install epel-release  && yum -y update glibc-common  && yum -y install bind-utils     gettext     hostname     procps-ng      rsync openssl && yum -y install --disablerepo="${PGDG_REPO_DISABLE}"     postgresql11-server postgresql11-contrib postgresql11 postgresql11-plpython    R-core libRmath plr11     postgis24_11 postgis24_11-client  pgrouting_11 && yum -y clean all": error while running runtime: exit status 1
make: *** [postgres-appdev] Error 1
```

It looks like both PostGIS 2.5 and PostGIS 2.4 are in there 🤔 

2. I would also suggest updating the corresponding UBI7 image in `ubi7/11/Dockerfile.postgres-appdev.ubi7`

Thanks!

2019-09-28 20:19 UTC, jkatz commented on centos7/11/Dockerfile.postgres-appdev.centos7
> + && yum -y um -y install --disablerepo="${PGDG_REPO_DISABLE}" \
This line breaks. It should be:

```docker
&& yum -y install --disablerepo="${PGDG_REPO_DISABLE}" \
```

2019-09-28 20:25 UTC, thesteve0 commented
I don't understand how the postgis container builds properly then

On Sat, Sep 28, 2019 at 1:19 PM Jonathan S. Katz <notifications@github.com>
wrote:

> *@jkatz* requested changes on this pull request.
>
> Tried building on CentOS 7. A few comments:
>
>    1. With the correction in the file mentioned in the comments, I get up
>    to this error before it fails:
>
> Transaction check error:
>
>   file /usr/pgsql-11/lib/address_standardizer.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/lib/bitcode/address_standardizer.index.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/lib/bitcode/address_standardizer/analyze.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/lib/bitcode/address_standardizer/parseaddress-api.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/lib/bitcode/address_standardizer/std_pg_hash.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/lib/liblwgeom.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/lib/postgis-2.4.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/lib/postgis_topology-2.4.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/lib/rtpostgis-2.4.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/share/extension/address_standardizer.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/share/extension/address_standardizer_data_us.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/share/extension/address_standardizer_data_us.sql conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/share/extension/postgis.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/share/extension/postgis_sfcgal.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/share/extension/postgis_tiger_geocoder.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>   file /usr/pgsql-11/share/extension/postgis_topology.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>
>
>
> Error Summary
>
> -------------
>
>
>
> error building at STEP "RUN yum -y update && yum -y install epel-release  && yum -y update glibc-common  && yum -y install bind-utils     gettext     hostname     procps-ng      rsync openssl && yum -y install --disablerepo="${PGDG_REPO_DISABLE}"     postgresql11-server postgresql11-contrib postgresql11 postgresql11-plpython    R-core libRmath plr11     postgis24_11 postgis24_11-client  pgrouting_11 && yum -y clean all": error while running runtime: exit status 1
>
> make: *** [postgres-appdev] Error 1
>
> It looks like both PostGIS 2.5 and PostGIS 2.4 are in there 🤔
>
>    1. I would also suggest updating the corresponding UBI7 image in
>    ubi7/11/Dockerfile.postgres-appdev.ubi7
>
> Thanks!
> ------------------------------
>
> In centos7/11/Dockerfile.postgres-appdev.centos7
> <https://github.com/CrunchyData/crunchy-containers/pull/1124#discussion_r329325306>
> :
>
> > @@ -27,9 +27,10 @@ RUN yum -y update && yum -y install epel-release \
>
>      hostname \
>
>      procps-ng  \
>
>      rsync openssl\
>
> - && yum -y install postgresql11-server postgresql11-contrib postgresql11 \
>
> + && yum -y um -y install --disablerepo="${PGDG_REPO_DISABLE}" \
>
>
> This line breaks. It should be:
>
> && yum -y install --disablerepo="${PGDG_REPO_DISABLE}" \
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CrunchyData/crunchy-containers/pull/1124?email_source=notifications&email_token=AAKWZQ7GJBSZ5EGSL6NZDBDQL6363A5CNFSM4I3JOW5KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCGIAS6A#pullrequestreview-294652280>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKWZQ6OHVU6LBH3PRZIKLLQL6363ANCNFSM4I3JOW5A>
> .
>

2019-09-28 20:27 UTC, thesteve0 commented
Nevermind , just read to the end I will try fixing the typo. Not moving to
UBI until the core team does

On Sat, Sep 28, 2019 at 1:25 PM Steven Pousty <steve.pousty@gmail.com>
wrote:

> I don't understand how the postgis container builds properly then
>
> On Sat, Sep 28, 2019 at 1:19 PM Jonathan S. Katz <notifications@github.com>
> wrote:
>
>> *@jkatz* requested changes on this pull request.
>>
>> Tried building on CentOS 7. A few comments:
>>
>>    1. With the correction in the file mentioned in the comments, I get
>>    up to this error before it fails:
>>
>> Transaction check error:
>>
>>   file /usr/pgsql-11/lib/address_standardizer.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/lib/bitcode/address_standardizer.index.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/lib/bitcode/address_standardizer/analyze.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/lib/bitcode/address_standardizer/parseaddress-api.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/lib/bitcode/address_standardizer/std_pg_hash.bc conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/lib/liblwgeom.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/lib/postgis-2.4.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/lib/postgis_topology-2.4.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/lib/rtpostgis-2.4.so conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/share/extension/address_standardizer.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/share/extension/address_standardizer_data_us.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/share/extension/address_standardizer_data_us.sql conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/share/extension/postgis.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/share/extension/postgis_sfcgal.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/share/extension/postgis_tiger_geocoder.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>   file /usr/pgsql-11/share/extension/postgis_topology.control conflicts between attempted installs of postgis25_11-2.5.3-5.rhel7.x86_64 and postgis24_11-2.4.8-5.rhel7.x86_64
>>
>>
>>
>> Error Summary
>>
>> -------------
>>
>>
>>
>> error building at STEP "RUN yum -y update && yum -y install epel-release  && yum -y update glibc-common  && yum -y install bind-utils     gettext     hostname     procps-ng      rsync openssl && yum -y install --disablerepo="${PGDG_REPO_DISABLE}"     postgresql11-server postgresql11-contrib postgresql11 postgresql11-plpython    R-core libRmath plr11     postgis24_11 postgis24_11-client  pgrouting_11 && yum -y clean all": error while running runtime: exit status 1
>>
>> make: *** [postgres-appdev] Error 1
>>
>> It looks like both PostGIS 2.5 and PostGIS 2.4 are in there 🤔
>>
>>    1. I would also suggest updating the corresponding UBI7 image in
>>    ubi7/11/Dockerfile.postgres-appdev.ubi7
>>
>> Thanks!
>> ------------------------------
>>
>> In centos7/11/Dockerfile.postgres-appdev.centos7
>> <https://github.com/CrunchyData/crunchy-containers/pull/1124#discussion_r329325306>
>> :
>>
>> > @@ -27,9 +27,10 @@ RUN yum -y update && yum -y install epel-release \
>>
>>      hostname \
>>
>>      procps-ng  \
>>
>>      rsync openssl\
>>
>> - && yum -y install postgresql11-server postgresql11-contrib postgresql11 \
>>
>> + && yum -y um -y install --disablerepo="${PGDG_REPO_DISABLE}" \
>>
>>
>> This line breaks. It should be:
>>
>> && yum -y install --disablerepo="${PGDG_REPO_DISABLE}" \
>>
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/CrunchyData/crunchy-containers/pull/1124?email_source=notifications&email_token=AAKWZQ7GJBSZ5EGSL6NZDBDQL6363A5CNFSM4I3JOW5KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCGIAS6A#pullrequestreview-294652280>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AAKWZQ6OHVU6LBH3PRZIKLLQL6363ANCNFSM4I3JOW5A>
>> .
>>
>

2019-09-28 20:29 UTC, jkatz commented
@thesteve0 RE UBI7, there is already a container in there for it:

https://github.com/CrunchyData/crunchy-containers/blob/develop/ubi7/11/Dockerfile.postgres-appdev.ubi7

If you do not want to use it, I'd suggest we remove it.

2019-11-18 05:20 UTC, jkatz commented
Closed in favor of #1146 and #1147

2019-11-18 05:20 UTC, closed without merging