Upgrade compaction
CrunchyData/crunchy-containers pull request #1306
Opened 2020-12-15 18:08 UTC by jmckulk

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change, as applicable?
 - [x] Have you tested your changes on all related environments with successful results, as applicable?

Tested an upgrade using centos7 images 

**Type of Changes:**

 
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**

**What is the new behavior (if this is a feature change)?**

**Other information**:

2020-12-16 20:01 UTC, jmckulk commented on bin/upgrade/start.sh
> +export PATH=/opt/crunchy/bin:${PGBINNEW?}:$PATH
needs to user CRUNCHY_DIR

2020-12-16 20:10 UTC, jkatz requested changes

2020-12-16 20:10 UTC, jkatz commented on bin/upgrade/start.sh
> +export PATH=/opt/crunchy/bin:${PGBINNEW?}:$PATH
^

2020-12-16 20:10 UTC, jkatz commented on bin/upgrade/start.sh
> +chmod 0700 ${PGDATAOLD?}
Should leave a comment here as this is an important line.

2020-12-16 21:37 UTC, jkatz requested changes

2020-12-16 21:37 UTC, jkatz commented on bin/upgrade/start.sh
> +export "PATH=${CRUNCHY_DIR}/bin:${PGBINNEW?}:$PATH"
```suggestion
export PATH="${CRUNCHY_DIR}/bin:${PGBINNEW?}:${PATH}"
```

2020-12-17 19:32 UTC, jkatz approved these changes

2020-12-17 19:56 UTC, merged