Add support for GCS storage for pgBackRest
CrunchyData/crunchy-containers pull request #1341
Opened 2021-04-12 02:33 UTC by jkatz

pgBackRest 2.33 introduced support for GCS storage. This adds
supported for GCS storage.

Issue: [ch11177]
CrunchyData/postgres-operator#2368

2021-04-12 14:26 UTC, tjmoore4 commented on bin/postgres-ha/pgbackrest/pgbackrest-archive-push-local-s3.sh
> +
:pick: looks like this space could just be removed?
```suggestion

```

2021-04-12 14:26 UTC, tjmoore4 commented on conf/pgbackrest-repo/aws-s3-credentials.yaml
> +gcs-key:
:thinking: Similar to the comment on the Operator side, would we want to either rename this file, or possibly create a separate one?
If renaming, perhaps something like 'cloud-storage-credentials.yaml' would be appropriate.

2021-04-13 16:57 UTC, andrewlecuyer commented on build/postgres/Dockerfile
> +ADD tmp/pgbackrest /usr/bin/pgbackrest
Was this intended? (thinking maybe something from your local pgBackRest build).

2021-04-13 18:13 UTC, andrewlecuyer requested changes
Looks great.  Noticed missing executable permissions on one of the new scripts that I was hoping could be adjusted, but otherwise just had a couple of questions around the use of the `pgbackrest.conf` file with `gcs` (not blockers).

2021-04-14 00:46 UTC, jkatz commented on bin/pgbackrest-repo/pgbackrest-repo.sh
> +  fi
@andrewlecuyer I was just adding what you add to ensure compatibility. If we don't need it, we don't need it.

2021-04-14 00:47 UTC, jkatz commented on bin/pgbackrest-repo/pgbackrest-repo.sh
> +  fi
See above comment :smile:

2021-04-14 01:01 UTC, andrewlecuyer approved these changes

2021-04-15 01:38 UTC, merged