release prep for v4.5.8
CrunchyData/crunchy-containers pull request #1474
Opened 2022-08-03 19:19 UTC by ValClarkson

[sc-15290]

**Checklist:**

 
 - [ ] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change, as applicable?
 - [ ] Have you tested your changes on all related environments with successful results, as applicable?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**

**What is the new behavior (if this is a feature change)?**

**Other information**:

2022-08-03 20:35 UTC, jmckulk requested changes
I don't think we should be deleting the crunchy theme submodule. Other than that things are looking good

2022-08-03 20:35 UTC, jmckulk commented on docs/content/examples/postgresql/custom-config-ssl.md
> +psql (11.17)
want to add the param here?

2022-08-03 20:36 UTC, ValClarkson commented on docs/content/examples/postgresql/custom-config-ssl.md
> +psql (11.17)
will do

2022-08-03 20:36 UTC, ValClarkson commented
> I don't think we should be deleting the crunchy theme submodule. Other than that things are looking good

I didn't mean to delete it completely good catch i'll get that fixed

2022-08-04 17:33 UTC, jmckulk approved these changes

2022-08-04 18:07 UTC, merged