[crunchy-postgres] Limit listener of temporary pg to unix domain socket
CrunchyData/crunchy-containers pull request #925
Opened 2018-12-05 12:06 UTC by gkranis

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change, as applicable?
 - [ ] Have you tested your changes on all related environments with successful results, as applicable?

**Type of Changes:**

 
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**

- The replica node uses `waitforpg` to detect when the master is ready for connections.
- Before the real master node comes up, a temporary master is used  in `initialize_primary`.
- There's a change that `waitforpg`, if fast enough, will connect to the temporary master node instead of the real one. 

Same issue as described here https://github.com/CrunchyData/crunchy-containers/issues/653

**What is the new behavior (if this is a feature change)?**
- Temporary primary listens only to unix domain socket (same approach that the official pg docker images [use](https://github.com/docker-library/postgres/blob/040949af1595f49f2242f6d1f9c42fb042b3eaed/10/docker-entrypoint.sh#L114-L116)).
- `pg_isready` in `initialize_primary` probes the unix domain socket instead of the ip
- The rest of `psql` commands in `initialize_primary` already used the unix domain socket so no change was needed
- `waitforpg` can't connect any more to the temporary primary

**Other information**:

Tested by patching those changes into `crunchydata/crunchy-postgres:centos7-10.5-2.1.0`. We just use a cluster of 2 initially empty crunchy-postgres in our CI run. Works for us :)

2018-12-06 15:57 UTC, jasonodonnell requested changes
Hi @gkranis,

Thanks for the patch, I have tested this and it works as expected.  I think it would make a good addition.

You will need to resubmit this pull request to the `develop` branch before we can approve this.

2018-12-10 10:35 UTC, gkranis commented
@jasonodonnell done

2018-12-10 14:18 UTC, merged

2018-12-14 14:46 UTC, longtimeago commented
@jasonodonnell would love to see the release with this fix. Thanks! :)

2018-12-14 14:54 UTC, jasonodonnell commented
@longtimeago This will be included in our 2.3.0 release which is scheduled for mid January.  Thanks!